# Generated by Django 5.0 on 2024-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuentoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="fecha_de_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="genero_literario",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
