# Generated by Django 5.0 on 2024-01-27 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuentoApp", "0002_autor_fecha_de_nacimiento_autor_genero_literario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autor",
            old_name="fecha_de_nacimiento",
            new_name="fecha_nacimiento",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="genero_literario",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="usuario",
        ),
        migrations.AddField(
            model_name="autor",
            name="apellido",
            field=models.CharField(default="apellido", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="autor",
            name="nombre",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
