# Generated by Django 5.0 on 2024-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CuentoApp",
            "0003_rename_fecha_de_nacimiento_autor_fecha_nacimiento_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuento",
            name="autores",
            field=models.ManyToManyField(related_name="autores", to="CuentoApp.autor"),
        ),
    ]
